services:
  phobos-runner:
    build:
      context: .
      dockerfile: Dockerfile

    security_opt:
      - "seccomp:./assets/seccomp_allow_bwrap.json"
      - "apparmor=docker-bwrap"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command:
      - -c
      - "exec /bin/bash"
