FROM maven:3.9.6-eclipse-temurin-17

MAINTAINER Stephan Krusche <krusche@tum.de>


RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libssl-dev \
    libnl-3-dev \
    bubblewrap \
    tree \
    python3 \
    strace \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -m sandboxuser

ADD test-repos /opt/test-repository
ADD student-exercises /opt/student-exercises


COPY pruning/ /opt/pruning/
COPY ld_preloader/ /opt/ld_preloader/
COPY core/ /opt/core/
COPY helpers/ /opt/helpers/

RUN gcc -shared -fPIC -ldl -o /opt/ld_preloader/libnetblocker.so /opt/ld_preloader/netblocker.c
RUN chown -R sandboxuser:sandboxuser /opt
RUN find /opt -type f -name '*.sh' -exec chmod 0755 {} +
USER sandboxuser


ENTRYPOINT []
# Set the default command to run the bwrap script
# CMD ["bash", "-c", "/opt/detect_minimal_fs.sh"]
CMD ["/bin/bash"]
# CMD ["/bin/bash","-c","/opt/detect_minimal_fs.sh --script /opt/build_script.sh --target /"]