services:
  prune_python:
    build: docker/prune_phase/python
    volumes:
      - type: bind
        source: ./var/tmp
        target: /var/tmp
    command: ["--verbose", "--cache-dir", "/home/sandboxuser/.cache/pip", "python"]

  #prune_java:
    #build: ./java
    #volumes:
      #- ./var/tmp:/var/tmp
    #command: ["--verbose", "--cache-dir", "/home/sandboxuser/.gradle", "java" ]

  prune_c:
    build: docker/prune_phase/c
    volumes:
      - type: bind
        source: ./var/tmp
        target: /var/tmp
    command: ["c"]

  orchestrate:
    build: docker/prune_phase/orchestrate
    volumes:
      - type: bind
        source: ./var/tmp
        target: /var/tmp
    depends_on:
      prune_python:
        condition: service_completed_successfully
      #prune_java:
        #condition: service_completed_successfully
      prune_c:
        condition: service_completed_successfully
    command:
      [
        "--langs", "python",
        "--path-dir", "/var/tmp/path_sets", "--skip-prune"
      ]
