services:
  prune_python:
    build: ./python
    volumes:
      - ../../var/tmp:/var/tmp
    command: ["python"]

  prune_java:
    build: ./java
    volumes:
      - ../../var/tmp:/var/tmp
    command: ["java"]

  prune_c:
    build: ./c
    volumes:
      - ../../var/tmp:/var/tmp
    command: ["c"]

  orchestrate:
    build: orchestrate
    volumes:
      - ../../var/tmp:/var/tmp
    depends_on:
      prune_python:
        condition: service_completed_successfully
      prune_java:
        condition: service_completed_successfully
      prune_c:
        condition: service_completed_successfully
    command:
      [
        "--langs", "java",
        "--path-dir", "/var/tmp/path_sets", "--skip-prune"
      ]
